## <font color = 'blue'> Notes on NumPy <font>

Source: https://www.w3schools.com/python/numpy_intro.asp

* library for working with large, multi-dimensional arrays.


* Created in 2005, it is an open source project that can be used freely.


* has functions for working in domain of linear algebra, fourier transform, and matrice


* NumPy(Numerical Python) arrays are **up to 50x faster than python lists**.


* <font color = 'red'>**import**<font color = 'black'> the numpy module <font color = 'red'>**as np**<font>

In [2]:
import numpy as np

In [3]:
# To check your version of numpy
print(np.__version__)

1.19.2


### <font color = 'red'>Creating Arrays<font color = 'black'>

The array object in NumPy is called ```ndarray```.

We can create a NumPy ndarray object by using the ```array()``` function.

In [4]:
my_array = np.array([1, 2, 3, 4, 5])

print(my_array)

print(type(my_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


You can pass a list, tuple or any array-like object into the ```array()``` method, and it will be converted into an ndarray:

In [6]:
# Example of converting a tuple to an array

tuple_to_array = np.array((1, 2, 3, 4, 5))
print(tuple_to_array)

[1 2 3 4 5]


In [17]:
# Example of specifying data type while creating array
arr = np.array([1, 2, 3, 4], dtype='S')

### <font color = 'red'>Dimensions in Arrays<font color = 'black'>

* A dimension in arrays is one level of array depth 

* nested array: an array that has arrays as its elements

    * 1-D arrays are the most common
    
    * <font color = 'red'>**2-D arrays** <font color = 'black'> are often used to represent a <font color = 'red'> **matrix**<font color = 'black'> 
    
* NumPy has a sub module for matrix operations called **numpy.mat**

In [7]:
# Example of creating 1-D array

my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


In [8]:
# Example of creating 2-D array

my_two_d = np.array([[1, 2, 3], [4, 5, 6]])
print(my_two_d)

[[1 2 3]
 [4 5 6]]


In [9]:
# How to check dimensions
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### <font color = 'red'>Accessing  Array Elements<font color = 'black'>

* Access an array element by referring to its index number.

* The indexes in NumPy arrays start with 0.

* Use negative indexing to access an array from the end.

* To access elements from 2-D arrays, use comma separated integers **[dimension, index]**

Example:  **Get the second element** from the following array.

In [10]:
arr = np.array([1, 2, 3, 4])
print(arr[1])

2


Example: Get third and fourth elements from the following array and add them.

In [11]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


Example: **Access the 5th element** on **2nd dimension**:

In [13]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd dim: ', arr[1, 4])

5th element on 2nd dim:  10


Example: Print the **last element** from the **2nd dimension**.

In [14]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


### <font color = 'red'>Data Types in NumPy<font color = 'black'>

NumPy refers to data types with one character:
    
    i - integer                  
    b - boolean                  
    u - unsigned integer         
    f - float                    
    c - complex float            
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed memory- other type (void)



In [15]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [16]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


For ```i```, ```u```, ```f```, ```S``` and ```U``` we can define size as well.

Example: Create an array with data type 4 bytes integer.

In [18]:
arr = np.array([1, 2, 3, 4], dtype='i4')

### <font color = 'red'> Iterating Arrays <font color = 'black'>

If we iterate on a 1-D array it will go through each element one by one:


In [19]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In a 2-D array it will go through **all** the rows:


In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


OR: 
To **return the actual values**, the scalars, we have to **iterate the arrays in each dimension**.

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [24]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


### <font color = 'red'> Filtering Arrays<font color = 'black'>
    
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

If the value at an index is True that element is contained in the filtered array, if it is False it is excluded.

**Example:** Create an array of elements greater than 42.

In [28]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


Example: Create a **filter array** that will return **only even elements** from the original array

In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


### <font color = 'red'>Filter Directly from Array<font color = 'black'>
    
We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.
    
**Example:** Create a filter array that will return only values higher than 42:





In [30]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
